questions:
  - id: 1
    question: "How many success attempts to create orders have occurred?"
    query: |
      {
        "query": {
          "bool": {
            "must": [
              { "match": { "tags": "orderservice" } },
              { "match_phrase": { "message": "requestURI: /orders httpMethod: POST Response Status: 200" } }
            ]
          }
        }
      }
  - id: 2
    question: "How many failed attempts to create orders have occurred?"
    query: |
      {
        "query": {
          "bool": {
            "must": [
              { "match": { "tags": "orderservice" } },
              { "match_phrase": { "message": "requestURI: /orders httpMethod: POST Response Status: 400" } }
            ]
          }
        }
      }
  # Add other questions similarly
